name: pp_2025
services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-backend
    volumes:
      - ./backend/src:/backend/src
    working_dir: /backend/src
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
  db:
    build:
      context: ./db
    container_name: postgres-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 5
      start_period: 10s
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    env_file:
      - .env
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped

  collabora:
    image: collabora/code
    container_name: collabora
    environment:
      - domain=backend
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
    ports:
      - "9980:9980"
    command: >
      --o:ssl.enable=false
      --o:ssl.termination=false
      --o:trusted.hosts=backend
    restart: always
    volumes:
      - collabora_data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - minio_data:/data
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    restart: always


volumes:
  pg_data:
  collabora_data:
  minio_data:
