name: pp_2025
services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/src:/backend/src
    working_dir: /backend/src
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    command: uvicorn main:app --reload --host 0.0.0.0
    ports:
      - "8000:8000"
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 5s
      retries: 5
      start_period: 10s

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend/src:/frontend/src
    ports:
      - "80:80"
    depends_on:
      - backend
volumes:
  pg_data:
