version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - ENV=local
    env_file:
      - .env
    volumes:
      - ./backend:/code
    working_dir: /code
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  db:
    build:
      context: ./db
    container_name: postgres-db
    ports:
      - "5433:5432"
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      retries: 10
      timeout: 20s
      start_period: 10s
    restart: always

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:80"  # ✅ Добавлен порт
    env_file:
      - .env
    volumes:
      - ./frontend:/app
      - /app/node_modules
    working_dir: /app
    command: npm run dev -- --host 0.0.0.0 --port 80
    depends_on:
      - backend
    restart: unless-stopped

  collabora:
    image: collabora/code
    container_name: collabora
    ports:
      - "9980:9980"
    environment:
      - domain=${COLLABORA_DOMAIN:-localhost}
      - username=${COLLABORA_USERNAME}
      - password=${COLLABORA_PASSWORD}
    command: >
      sh -c "exec loolwsd --o:ssl.enable=false
                              --o:ssl.termination=false
                              --o:trusted.hosts=frontend
                              --o:trusted.hosts=backend
                              --o:storage.filesystem=/tmp"
    restart: always
    volumes:
      - collabora_data:/data

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    volumes:
      - minio_data:/data
    command: server /data --console-address :9001
    restart: always

volumes:
  pg_data:
  collabora_data:
  minio_data: